# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff609dc727c0dca7859f5700ca7b8c98b18a29c516f6c7ab4064a31fc6b8dfa26288820de9de730f4e0e684793dca7e9400fabd64521879c8858de627c8eab5e

test:
  secret_key_base: 902c7b57e2e95e4ad652ba196b00146267bff5643746f813e357e4143bca6e086729e5326b5e091c33bad065cfe5ec8e55d1718fe49dcb709da5bc2da21b83dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
